ckeditor5_premium_features_export_word.settings:
  type: config_object
  label: 'CKEditor 5 Premium Features - Export to PDF'
  mapping:
    coverter_url:
      type: string
      label: 'Converter URL'
    converter_options:
      type: mapping
      label: 'Converter options'
      mapping:
        format:
          type: string
          label: 'Page format'
        margin_top:
          type: string
          label: 'Margin top'
        margin_bottom:
          type: string
          label: 'Margin bottom'
        margin_left:
          type: string
          label: 'Margin left'
        margin_right:
          type: string
          label: 'Margin right'
        header:
          type: string
          label: 'Header'
        footer:
          type: string
          label: 'Footer'
