<?php

/**
 * @file
 * Contains CKEditor 5 Premium Features Realtime module functions.
 */

declare(strict_types = 1);

use Drupal\ckeditor5_premium_features\Utility\LibraryDefinitionItem;
use Drupal\ckeditor5_premium_features_realtime\Element\TextFormat;
use Drupal\Component\Utility\Crypt;

/**
 * Implements hook_library_info_build().
 */
function ckeditor5_premium_features_realtime_library_info_build(): array {
  /** @var \Drupal\ckeditor5_premium_features\Config\SettingsConfigHandlerInterface $config_handler */
  $config_handler = \Drupal::service('ckeditor5_premium_features.config_handler.settings');

  $libraries = [
    'ckeditor5-collaboration-dll',
    'real-time-collaboration',
    'comments',
    'revision-history',
    'track-changes',
  ];

  $definitions = [];

  foreach ($libraries as $library) {
    $definition = new LibraryDefinitionItem($library, $config_handler->getDllLocation());
    $definition->addRemoteJs($definition->id());

    $definitions[$definition->id()] = $definition->getDefinition();
  }

  return $definitions;
}

/**
 * Implements hook_element_info_alter().
 */
function ckeditor5_premium_features_realtime_element_info_alter(array &$info): void {
  if (isset($info['text_format'])) {
    $info['text_format']['#process'][] = [TextFormat::class, 'process'];
  }
}

function ckeditor5_premium_features_realtime_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  $input = $form_state->getUserInput();
  if (!empty($input) && $input['channelId']) {
    $channelId = $input['channelId'];
  }
  else {
    $channelId = Crypt::randomBytesBase64(24);
  }
  $form['channelId'] = [
    '#type' => 'hidden',
    '#value' => $channelId,
    '#default_value' => $channelId,
  ];
}

