<?php

/**
 * @file
 * Implements hooks for the CKEditor 5 Premium Features module.
 */

declare(strict_types = 1);

use Drupal\Component\Utility\Html;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\ckeditor5_premium_features\Utility\LibraryDefinitionItem;
use Drupal\ckeditor5_premium_features\EditorXssFilter\CollaborationXSSFilter;
use Drupal\filter\FilterFormatInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function ckeditor5_premium_features_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.ckeditor5_premium_features':
      $text = file_get_contents(__DIR__ . '/README.md');
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . Html::escape($text) . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
      # TODO: Load text from Readme.md
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The CKEditor Premium Features, see <a href=":doc_url">online documentation for the CKEditor Premium Features</a>.', [':doc_url' => 'https://ckeditor.com/docs/trial/latest/guides/overview.html']) . '</p>';
      return $output;
  }
}

/**
 * Implements hook_library_info_build().
 */
function ckeditor5_premium_features_library_info_build(): array {
  /** @var \Drupal\ckeditor5_premium_features\Config\SettingsConfigHandlerInterface $config_handler */
  $config_handler = \Drupal::service('ckeditor5_premium_features.config_handler.settings');

  $libraries = [
    'ckeditor5-collaboration-dll',
    'cloud-services',
  ];

  $definitions = [];

  foreach ($libraries as $library) {
    $definition = new LibraryDefinitionItem($library, $config_handler->getDllLocation());
    $definition->addRemoteJs($definition->id());

    $definitions[$definition->id()] = $definition->getDefinition();
  }

  return $definitions;
}

/**
 * Implements hook_editor_xss_filter_alter().
 */
function ckeditor5_premium_features_editor_xss_filter_alter(
  &$editor_xss_filter_class,
  FilterFormatInterface $format,
  FilterFormatInterface $original_format = NULL) {
  $editor_xss_filter_class = CollaborationXSSFilter::class;
}

/**
 * Callback for export to Word header buttons (add/remove).
 */
function headerAddMoreWordCallback(array &$form, FormStateInterface $form_state): ?array {
  $settings_element = $form['editor']['settings']['subform']['plugins']['ckeditor5_premium_features_export_word__export_word'] ?? $form;

  return $settings_element['converter_options']['header'] ?? NULL;
}

/**
 * Callback for export to Word footer buttons (add/remove).
 */
function footerAddMoreWordCallback(array &$form, FormStateInterface $form_state): ?array {
  $settings_element = $form['editor']['settings']['subform']['plugins']['ckeditor5_premium_features_export_word__export_word'] ?? $form;

  return $settings_element['converter_options']['footer'] ?? NULL;
}

/**
 * Submit handler for the header "add-one-more" button.
 */
function headerAddOne(array &$form, FormStateInterface $form_state): void {
  _modifyItemCounter($form_state, 'num_headers', 1);
}

/**
 * Submit handler for the footer "add-one-more" button.
 */
function footerAddOne(array &$form, FormStateInterface $form_state) : void{
  _modifyItemCounter($form_state, 'num_footers', 1);
}

/**
 * Submit handler for the header "remove-one" button.
 */
function headerRemoveCallback(array &$form, FormStateInterface $form_state): void {
  _modifyItemCounter($form_state, 'num_headers');
}

/**
 * Submit handler for the footer "remove-one" button.
 */
function footerRemoveCallback(array &$form, FormStateInterface $form_state): void {
  _modifyItemCounter($form_state, 'num_footers');
}

/**
 * Increments or decrements the items max counter and causes a rebuild.
 *
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   Form state object.
 * @param string$counter_name
 *   Name of property to modify.
 * @param int $modifier
 *   Value to modify the counter.
 *
 * @return void
 */
function _modifyItemCounter(FormStateInterface $form_state, string $counter_name, int $modifier = -1): void {
  $name_field = $form_state->get($counter_name);
  if ($modifier > 0 || $name_field > abs($modifier)) {
    $remove_button = $name_field + $modifier;
    $form_state->set($counter_name, $remove_button);
  }

  $form_state->setRebuild();
}
