<?php

/**
* @file
* Install and update hooks for the CKEditor 5 Premium Features module.
*/

use Drupal\Core\Database\Database;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Change uid field to nullable.
 */
function ckeditor5_premium_features_update_9001() {
  $schema = Database::getConnection()->schema();
  $schema->changeField('ckeditor5_revision', 'uid', 'uid', [
    'not null' => FALSE,
    'mysql_type' => 'INT(10)',
    'unsigned' => TRUE,
  ]);
}

function ckeditor5_premium_features_update_9003() {

     $storage_definition = BaseFieldDefinition::create('string_long')
                                 ->setLabel(t('Message item event type.'))
                                 ->setDescription(t('The message content.'));

       \Drupal::entityDefinitionUpdateManager()
         ->installFieldStorageDefinition('message_content', 'ckeditor5_message_item', 'ckeditor5_message_item', $storage_definition);
}

