<?php

/**
 * @file
 * Conatains CKEditor 5 Premium Features Comments module functions.
 */

declare(strict_types = 1);

use Drupal\ckeditor5_premium_features\Utility\LibraryDefinitionItem;

/**
 * Implements hook_library_info_build().
 */
function ckeditor5_premium_features_comments_library_info_build(): array {
  /** @var \Drupal\ckeditor5_premium_features\Config\SettingsConfigHandlerInterface $config_handler */
  $config_handler = \Drupal::service('ckeditor5_premium_features.config_handler.settings');

  $library = new LibraryDefinitionItem('comments', $config_handler->getDllLocation());
  $library->addRemoteJs($library->id());
  $library->addDependency('ckeditor5_premium_features_collaboration/ckeditor5-collaboration-dll');

  $libraries[$library->id()] = $library->getDefinition();

  return $libraries;
}
