ckeditor5_premium_features_productivity_pack_templates.ckeditor5_templates.*:
  type: config_entity
  label: CKEditor5 Content Template
  mapping:
    id:
      type: string
      label: ID
    uuid:
      type: string
    label:
      type: label
      label: Title
    description:
      type: string
      label: Description
    icon:
      type: string
      label: Icon
    data:
      type: string
      label: HTML code
    formats:
      type: sequence
      label: Available for
    weight:
      type: integer
      label: Weight
    status:
      type: boolean
      label: Enabled
