<?php

/*
 * Copyright (c) 2003-2023, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see https://ckeditor.com/legal/ckeditor-oss-license
 */

use Drupal\ckeditor5_premium_features\Utility\LibraryDefinitionItem;
use Drupal\ckeditor5_premium_features_productivity_pack\Element\TextFormat;

/**
 * Implements hook_element_info_alter().
 */
function ckeditor5_premium_features_productivity_pack_element_info_alter(array &$info): void {
  if (isset($info['text_format'])) {
    $info['text_format']['#process'][] = [TextFormat::class, 'process'];
  }
}
/**
 * Implements hook_library_info_build().
 */
function ckeditor5_premium_features_productivity_pack_library_info_build(): array {
  /** @var \Drupal\ckeditor5_premium_features\Config\SettingsConfigHandlerInterface $config_handler */
  $config_handler = \Drupal::service('ckeditor5_premium_features.config_handler.settings');

  $libraries = [
    'format-painter',
    'document-outline',
    'template',
    'slash-command',
    'paste-from-office-enhanced'
  ];

  $definitions = [];

  foreach ($libraries as $library) {
    $definition = new LibraryDefinitionItem($library, $config_handler->getDllLocation());
    $definition->addRemoteJs($definition->id());

    $definitions[$definition->id()] = $definition->getDefinition();
  }

  return $definitions;

}

/**
 * Implements hook_library_info_alter().
 */
function ckeditor5_premium_features_productivity_pack_library_info_alter(&$libraries, $extension): void {
  // Do not load Paste from Office Enhanced if CKEditor version doesn't support it.
  if ($extension == 'ckeditor5_premium_features_productivity_pack') {
    if (!\Drupal::service('ckeditor5_premium_features.core_library_version_checker')->isLibraryVersionHigherOrEqual('39.0.0')) {
      unset($libraries["paste-from-office-enhanced"]);
    }
  }
}

/**
 * Implements hook_ckeditor5_plugin_info_alter().
 */
function ckeditor5_premium_features_productivity_pack_ckeditor5_plugin_info_alter(array &$plugin_definitions): void {
  // Do not load Paste from Office Enhanced if CKEditor version doesn't support it.
  if (!\Drupal::service('ckeditor5_premium_features.core_library_version_checker')->isLibraryVersionHigherOrEqual('39.0.0')) {
    unset($plugin_definitions["ckeditor5_premium_features_productivity_pack_paste_from_office_enhanced"]);
  }
}

