<?php

use Drupal\ckeditor5_premium_features\Utility\LibraryDefinitionItem;

/**
 * Implements hook_library_info_build().
 */
function ckeditor5_premium_features_productivity_pack_library_info_build(): array {
  /** @var \Drupal\ckeditor5_premium_features\Config\SettingsConfigHandlerInterface $config_handler */
  $config_handler = \Drupal::service('ckeditor5_premium_features.config_handler.settings');

  $libraries = [
    'format-painter',
    'document-outline',
    'slash-command',
  ];

  $definitions = [];

  foreach ($libraries as $library) {
    $definition = new LibraryDefinitionItem($library, $config_handler->getDllLocation());
    $definition->addRemoteJs($definition->id());

    $definitions[$definition->id()] = $definition->getDefinition();
  }

  return $definitions;

}
