<?php

/**
 * @file
 * Implements hooks for the CKEditor 5 Premium Features Collaboration module.
 */

declare(strict_types=1);

use Drupal\ckeditor5_premium_features\Utility\LibraryDefinitionItem;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_library_info_build().
 */
function ckeditor5_premium_features_collaboration_library_info_build(): array {
  /** @var \Drupal\ckeditor5_premium_features\Config\SettingsConfigHandlerInterface $config_handler */
  $config_handler = \Drupal::service('ckeditor5_premium_features.config_handler.settings');

  $ck_collaboration_dll = new LibraryDefinitionItem('ckeditor5-collaboration-dll', $config_handler->getDllLocation());
  $ck_collaboration_dll->addRemoteJs($ck_collaboration_dll->id());

  $track_changes = new LibraryDefinitionItem('track-changes', $config_handler->getDllLocation());
  $track_changes->addRemoteJs($track_changes->id());

  $comments = new LibraryDefinitionItem('comments', $config_handler->getDllLocation());
  $comments->addRemoteJs($comments->id());

  return [
    $ck_collaboration_dll->id() => $ck_collaboration_dll->getDefinition(),
    $track_changes->id() => $track_changes->getDefinition(),
    $comments->id() => $comments->getDefinition(),
  ];
}

/**
 * Implements hook_element_info_alter().
 *
 * @see \Drupal\filter\Element\TextFormat
 */
function ckeditor5_premium_features_collaboration_field_widget_single_element_form_alter(array &$element, FormStateInterface $form_state, array $context) : void {
  $type = $element['#type'] ?? NULL;

  if ($type !== 'text_format') {
    return;
  }

  /** @var \Drupal\Core\Field\FieldItemListInterface|null $items */
  $items = $context['items'] ?? NULL;
  $entity = $items?->getEntity();

  if ($entity instanceof EntityInterface) {
    $entity_context = [
      'data-entity' => $entity->id(),
      'data-entity-type' => $entity->getEntityTypeId(),
    ];
    $element['#attributes'] = $entity_context + $element['#attributes'];
  }

  /** @var \Drupal\ckeditor5_premium_features_collaboration\Service\MarkupDataProviderInterface $data_provider */
  $data_provider = \Drupal::service('ckeditor5_premium_features_collaboration.makrup_data_provider');
  $content = $element['#default_value'] ?? '';
  $element['#attached']['drupalSettings']['ckeditor5Premium']['users'] = $data_provider->getSuggestionsUsers($content);
}
