<?php

/**
 * @file
 * Implements hooks for the CKEditor 5 Premium Features Collaboration module.
 */

declare(strict_types=1);

use Drupal\ckeditor5_premium_features\Utility\LibraryDefinitionItem;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\ckeditor5_premium_features_collaboration\Element\MentionsIntegration;
use Drupal\ckeditor5_premium_features_collaboration\Element\TextFormat;

/**
 * Implements hook_library_info_build().
 */
function ckeditor5_premium_features_collaboration_library_info_build(): array {
  /** @var \Drupal\ckeditor5_premium_features\Config\SettingsConfigHandlerInterface $config_handler */
  $config_handler = \Drupal::service('ckeditor5_premium_features.config_handler.settings');

  $libraries = [
    'track-changes',
    'comments',
    'revision-history',
    'mention',
  ];

  $definitions = [];

  foreach ($libraries as $library) {
    $definition = new LibraryDefinitionItem($library, $config_handler->getDllLocation());
    $definition->addRemoteJs($definition->id());

    $definitions[$definition->id()] = $definition->getDefinition();
  }

  return $definitions;
}

/**
 * Implements hook_element_info_alter().
 *
 * @see \Drupal\filter\Element\TextFormat
 */
function ckeditor5_premium_features_collaboration_field_widget_single_element_form_alter(array &$element, FormStateInterface $form_state, array $context) : void {
  $type = $element['#type'] ?? NULL;

  if ($type !== 'text_format') {
    return;
  }

  /** @var \Drupal\Core\Field\FieldItemListInterface|null $items */
  $items = $context['items'] ?? NULL;
  $entity = $items?->getEntity();

  if ($entity instanceof EntityInterface) {
    $entity_context = [
      'data-entity' => $entity->id(),
      'data-entity-type' => $entity->getEntityTypeId(),
    ];
    $element['#attributes'] = $entity_context + $element['#attributes'];
  }
}

/**
 * Implements hook_element_info_alter().
 */
function ckeditor5_premium_features_collaboration_element_info_alter(array &$info): void {
  if (isset($info['text_format'])) {
    $info['text_format']['#process'][] = [TextFormat::class, 'process'];
    $info['text_format']['#process'][] = [MentionsIntegration::class, 'process'];
  }
}

/**
 * Implements hook_form_alter().
 */
function ckeditor5_premium_features_collaboration_form_alter(&$form, FormStateInterface $form_state) {
  TextFormat::processFormWithCollaborationStorage($form, $form_state);
}
