<?php

/**
 * @file
 * Implements hooks for the CKEditor 5 Premium Features Collaboration module.
 */

declare(strict_types = 1);

use Drupal\ckeditor5_premium_features\Utility\LibraryDefinitionItem;

/**
 * Implements hook_library_info_build().
 */
function ckeditor5_premium_features_collaboration_library_info_build(): array {
  /** @var \Drupal\ckeditor5_premium_features\Config\SettingsConfigHandlerInterface $config_handler */
  $config_handler = \Drupal::service('ckeditor5_premium_features.config_handler.settings');

  $library = new LibraryDefinitionItem('ckeditor5-collaboration-dll', $config_handler->getDllLocation());
  $library->addRemoteJs($library->id());

  $libraries[$library->id()] = $library->getDefinition();

  return $libraries;
}
