<?php

/**
 * @file
 * Conatains CKEditor 5 Premium Features Notifications module functions.
 */

declare(strict_types=1);

use Drupal\ckeditor5_premium_features_collaboration\Entity\CommentInterface;
use Drupal\ckeditor5_premium_features_collaboration\Entity\SuggestionInterface;
use Drupal\ckeditor5_premium_features_collaboration\Event\CollaborationEventBase;
use Drupal\ckeditor5_premium_features_notifications\Entity\Message;
use Drupal\ckeditor5_premium_features_notifications\Plugin\Notification\NotificationMessageFactoryDefault;
use Drupal\Core\Render\BubbleableMetadata;
use Drupal\user\Entity\User;

/**
 * Implements hook_mail().
 */
function ckeditor5_premium_features_notifications_mail($key, &$message, $params) {
  if (!NotificationMessageFactoryDefault::isMessageTypeSupported($key)) {
    return;
  }

  $message['subject'] = $params['subject'];
  $message['body'] = $params['body'];
  $message['headers'] += $params['headers'];
}

/**
 * Implements hook_tokens().
 */
function ckeditor5_premium_features_notifications_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleableMetadata) {
  if ($type != 'suggestion' || !isset($data['suggestion']) || !$data['suggestion'] instanceof CollaborationEventBase) {
    return [];
  }

  /** @var \Drupal\ckeditor5_premium_features_collaboration\Event\CollaborationEventBase $suggestion */
  $suggestion = $data['suggestion'];

  $replacements = [];
  foreach ($tokens as $name => $original) {
    switch ($name) {
      case 'status':
        $replacements[$original] = $suggestion->getEventType();
        break;
      case 'status-label':
        try {
          $replacements[$original] = t(CollaborationEventBase::getEventLabel($suggestion->getEventType()));
        }
        catch (Exception) {}
        break;
    }
  }

  return $replacements;
}

/**
 * Implements hook_cron().
 */
function ckeditor5_premium_features_notifications_cron()
{

  $storage = \Drupal::entityTypeManager()->getStorage(Message::ENTITY_TYPE_ID);
  $nids = $storage->getQuery()
    ->accessCheck(FALSE)
    ->condition('sent', 0)
    ->sort('created', 'ASC')
    ->range(0, 10)
    ->execute();

  if ($nids) {
    $nodes = \Drupal::entityTypeManager()->getStorage(Message::ENTITY_TYPE_ID)->loadMultiple($nids);
    //$frst_node = reset($nodes);
  }

foreach ($nodes as $frst_node) {

  $messageItems = $frst_node->getItems(); //message entity id
  $thread = [];
  $body = '';
  foreach ($messageItems as $messageItem) {
    $entityId = $messageItem->get('entity_id')->getString();
    switch ($messageItem->get('message_type')->getString()) {
      case 'ckeditor5_message_thread_reply':

        $comment = \Drupal::entityTypeManager()->getStorage(CommentInterface::ENTITY_TYPE_ID)->loadByProperties(
          [
            'id' => $entityId,
          ]
        );
        $comment = reset($comment);
        $comments = \Drupal::entityTypeManager()->getStorage(CommentInterface::ENTITY_TYPE_ID)->loadByProperties(
          [
            'thread_id' => $comment->getThreadId(),
          ]
        );

        foreach ($comments as $singleComment) {
          $thread[$singleComment->getPosition()] = $singleComment->getContent();
        }
        ksort($thread);

        foreach ($thread as $tmess) {
          $body .= $tmess . "\n";
        }
        $body .= "-------------------------------------\n";
        $messageItem->delete();
        break;

      case 'ckeditor5_message_suggestion_reply' :
        $comment = \Drupal::entityTypeManager()->getStorage(CommentInterface::ENTITY_TYPE_ID)->loadByProperties(
          [
            'id' => $entityId,
          ]
        );
        $comment = reset($comment);
        $suggestion = \Drupal::entityTypeManager()->getStorage(SuggestionInterface::ENTITY_TYPE_ID)->loadByProperties(
          [
            'id' => $comment->getThreadId(),
          ]
        );
        $suggestion = reset($suggestion);
        $context = \Drupal::entityTypeManager()->getStorage(\Drupal\ckeditor5_premium_features_notifications\Entity\MessageItemInterface::ENTITY_TYPE_ID)->loadByProperties(
          [
            'entity_id' => $entityId,
            'event_type' => 'ck5_collaboration_suggestion_added',
          ]
        );
        $context = reset($context);
        if ($context) {
          $context = $context->get('message_content')->getString();
          $begin = strpos($context, '<comment-start name="' . $comment->getThreadId());
          if ($begin) {
            $end = strpos($context, '<comment-end name="' . $comment->getThreadId());
            $rest = substr($context, $begin, $end - $begin);
            $body .= $rest . "\n";
          }
        }
        $body .= '$suggestion->getContent()';
        $comments = \Drupal::entityTypeManager()->getStorage(CommentInterface::ENTITY_TYPE_ID)->loadByProperties(
          [
            'thread_id' => $comment->getThreadId(),
          ]
        );

        foreach ($comments as $singleComment) {
          $thread[$singleComment->getPosition()] = $singleComment->getContent();
        }
        ksort($thread);

        foreach ($thread as $tmess) {
          $body .= $tmess . "\n";
        }
        $body .= "-------------------------------------\n";
        $messageItem->delete();
        break;

      case 'ckeditor5_message_suggestion_status' :
        if ($messageItem->get('event_type')->getString() == 'ck5_collaboration_comment_added') {
          break;
        }
        $body .= "Your suggestion is accepted\n";
        $context = \Drupal::entityTypeManager()->getStorage(\Drupal\ckeditor5_premium_features_notifications\Entity\MessageItemInterface::ENTITY_TYPE_ID)->loadByProperties(
          [
            'entity_id' => $entityId,
            'event_type' => 'ck5_collaboration_suggestion_added',
          ]
        );
        $context = reset($context);
        if ($context) {
          $context = $context->get('message_content')->getString();
          $begin = strpos($context, '<suggestion-start name="insertion:' . $entityId);
          if ($begin) {
            $end = strpos($context, '<suggestion-end name="insertion:' . $entityId);
            $rest = substr($context, $begin, $end - $begin);
            $body .= $rest . "\n";
          }
        }/*
        $comments = \Drupal::entityTypeManager()->getStorage(CommentInterface::ENTITY_TYPE_ID)->loadByProperties(
          [
            'thread_id' => $comment->getThreadId(),
          ]
        );

        foreach ($comments as $singleComment) {
          $thread[$singleComment->getPosition()] = $singleComment->getContent();
        }
        ksort($thread);

        foreach ($thread as $tmess) {
          $body .= $tmess . "\n";
        }*/
        $body .= "-------------------------------------\n";
        $messageItem->delete();
        break;

      case 'ckeditor5_message_mention_comment' :
        $body .= "You are mentioned in comment:\n\n";
        $comment = \Drupal::entityTypeManager()->getStorage(CommentInterface::ENTITY_TYPE_ID)->loadByProperties(
          [
            'id' => $entityId,
          ]
        );
        $comment = reset($comment);
        $context = $messageItem->get('message_content')->getString();
        $begin = strpos($context, '<comment-start name="' . $comment->getThreadId());
        if ($begin) {
          $end = strpos($context, '<comment-end name="' . $comment->getThreadId());
          $rest = substr($context, $begin, $end - $begin);
          $body .= $rest . "\n";
        }

        $body .= $comment->getContent();
        $body .= "-------------------------------------\n";
        $messageItem->delete();
        break;

      case 'ckeditor5_message_mention_document' :
        $nid = $frst_node->get('entity_id')->getString();
        $node = \Drupal\node\Entity\Node::load($nid);
        $body .= "You are mentioned in document: <a href=\"ckeditor5.localhost/node/" . $nid ."/edit\">" . $node->getTitle() . "</a>" . "\n";
        $body .= "-------------------------------------\n";
        $messageItem->delete();
        break;
    }
  }

  $userId = $frst_node->get('uid')->getString();
  $user = User::load($userId);

  $mailManager = \Drupal::service("plugin.manager.mail");
  $params["context"]["subject"] = "Test mail subject.";
  $params["context"]["message"] = $body;
  $to = $user->getEmail(); //Email needs to be sent
  $result = $mailManager->mail("system", "mail", $to, 'pl', $params);
  \Drupal::messenger()->addMessage('Cron task done');
  //$frst_node->set('sent', 1);
  //$frst_node->save();
}
}
