<?php

/**
 * @file
 * Conatains CKEditor 5 Premium Features Notifications module installer.
 */

declare(strict_types=1);

use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\ckeditor5_premium_features_notifications\Entity\MessageItemInterface;

/**
 * Implements hook_install().
 */
function ckeditor5_premium_features_notifications_install($is_syncing) {
  /** @var \Drupal\Core\Config\ConfigFactory $configFactory */
  $configFactory = \Drupal::service('config.factory');
  $userFormConfig = $configFactory->getEditable('core.entity_form_display.user.user.default');

  if (!$userFormConfig) {
    return;
  }

  $configArray = $userFormConfig->getRawData();
  if (isset($configArray['content']['field_ck5_premium_notifications'])) {
    return;
  }

  unset($configArray['hidden']['field_ck5_premium_notifications']);
  $configArray['content']['field_ck5_premium_notifications'] = [
    'type' => 'boolean_checkbox',
    'weight' => 0,
    'region' => 'content',
    'settings' => [],
    'third_party_settings' => [],
  ];

  $userFormConfig->setData($configArray)->save();
}

/**
 * Implements hook_update().
 */
function ckeditor5_premium_features_notifications_update_9001() {
  $storageDefinition = BaseFieldDefinition::create('string_long')
    ->setLabel(t('Message item event type.'))
    ->setDescription(t('The message content.'));

  $entityDefinition = \Drupal::entityDefinitionUpdateManager();
  $messageItem = $entityDefinition->getEntityType('ckeditor5_message_item');

  if ($messageItem) {
    $entityDefinition->installFieldStorageDefinition(
      'message_content',
      'ckeditor5_message_item',
      'ckeditor5_message_item',
      $storageDefinition
    );
  }
}

/**
 * Implements hook_update().
 */
function ckeditor5_premium_features_notifications_update_9006() {
  $storageDefinitionUid = BaseFieldDefinition::create('entity_reference')
    ->setLabel(t('User'))
    ->setSetting('target_type', 'user')
    ->setRequired(TRUE);
  $storageDefinitionCreated = BaseFieldDefinition::create('created')
    ->setLabel(t('Created'))
    ->setRequired(TRUE);

  $entityDefinition = \Drupal::entityDefinitionUpdateManager();
  $messageItemUserReference = $entityDefinition->getFieldStorageDefinition('created', MessageItemInterface::ENTITY_TYPE_ID);

  if (!$messageItemUserReference) {
    $entityDefinition->installFieldStorageDefinition(
      'uid',
      MessageItemInterface::ENTITY_TYPE_ID,
      MessageItemInterface::ENTITY_TYPE_ID,
      $storageDefinitionUid
    );
    $entityDefinition->installFieldStorageDefinition(
      'created',
      MessageItemInterface::ENTITY_TYPE_ID,
      MessageItemInterface::ENTITY_TYPE_ID,
      $storageDefinitionCreated
    );
  }
}
