<?php

/**
 * @file
 * Conatains CKEditor 5 Premium Features Notifications module installer.
 */

declare(strict_types=1);

use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_install().
 */
function ckeditor5_premium_features_notifications_install($is_syncing) {
  /** @var \Drupal\Core\Config\ConfigFactory $configFactory */
  $configFactory = \Drupal::service('config.factory');
  $userFormConfig = $configFactory->getEditable('core.entity_form_display.user.user.default');

  if (!$userFormConfig) {
    return;
  }

  $configArray = $userFormConfig->getRawData();
  if (isset($configArray['content']['field_ck5_premium_notifications'])) {
    return;
  }

  unset($configArray['hidden']['field_ck5_premium_notifications']);
  $configArray['content']['field_ck5_premium_notifications'] = [
    'type' => 'boolean_checkbox',
    'weight' => 0,
    'region' => 'content',
    'settings' => [],
    'third_party_settings' => [],
  ];

  $userFormConfig->setData($configArray)->save();
}

/**
 * Implements hook_update().
 */
function ckeditor5_premium_features_notifications_update_9001() {
   $storage_definition = BaseFieldDefinition::create('string_long')
     ->setLabel(t('Message item event type.'))
     ->setDescription(t('The message content.'));

   \Drupal::entityDefinitionUpdateManager()
     ->installFieldStorageDefinition('message_content', 'ckeditor5_message_item', 'ckeditor5_message_item', $storage_definition);
}
