<?php

/*
 * Copyright (c) 2003-2023, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see https://ckeditor.com/legal/ckeditor-oss-license
 */

/**
 * @file
 * Contains CKEditor 5 Premium Features Realtime module functions.
 */

declare(strict_types = 1);

use Drupal\ckeditor5_premium_features\Utility\LibraryDefinitionItem;
use Drupal\ckeditor5_premium_features_productivity_pack\Element\TextFormat as TextFormatProductivityPack;
use Drupal\ckeditor5_premium_features_realtime_collaboration\Element\TextFormat;
use Drupal\ckeditor5_premium_features_realtime_collaboration\Entity\ChannelInterface;
use Drupal\Component\Serialization\Json;
use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\EntityInterface;
use Drupal\editor\Entity\Editor;

/**
 * Implements hook_library_info_build().
 */
function ckeditor5_premium_features_realtime_collaboration_library_info_build(): array {
  /** @var \Drupal\ckeditor5_premium_features\Config\SettingsConfigHandlerInterface $config_handler */
  $config_handler = \Drupal::service('ckeditor5_premium_features.config_handler.settings');

  $libraries = [
    'real-time-collaboration',
    'comments',
    'revision-history',
    'track-changes',
  ];

  $definitions = [];

  foreach ($libraries as $library) {
    $definition = new LibraryDefinitionItem($library, $config_handler->getDllLocation());
    $definition->addRemoteJs($definition->id());

    $definitions[$definition->id()] = $definition->getDefinition();
  }

  return $definitions;
}

/**
 * Implements hook_element_info_alter().
 */
function ckeditor5_premium_features_realtime_collaboration_element_info_alter(array &$info): void {
  if (isset($info['text_format'])) {
    $moduleHandler = \Drupal::service('module_handler');
    $isOrderChanged = FALSE;
    if ($moduleHandler->moduleExists('ckeditor5_premium_features_productivity_pack')) {
      $isOrderChanged = ckeditor5_premium_features_realtime_collaboration_validate_text_format_order($info);
    }
    if (!$isOrderChanged) {
      $info['text_format']['#process'][] = [TextFormat::class, 'process'];
    }
  }
}

/**
 * Extra check to make sure that the productivity pack is loaded after rtc module.
 *
 * @param array $info
 *   Info array.
 *
 * @return bool
 *   TRUE if order has been changed.
 */
function ckeditor5_premium_features_realtime_collaboration_validate_text_format_order(array &$info):bool {
  if (isset($info['text_format']['#process'])) {
    foreach ($info['text_format']['#process'] as $key => $process) {
      if (current($process) === TextFormatProductivityPack::class) {
        $info['text_format']['#process'][$key] = [TextFormat::class, 'process'];
        $info['text_format']['#process'][] = $process;
        return TRUE;
      }
    }
  }
  return FALSE;
}

/**
 * Implements hook_entity_delete().
 *
 * Remove ckeditor5_channel entities after parent entity is deleted.
 */
function ckeditor5_premium_features_realtime_collaboration_entity_delete(EntityInterface $entity): void {
  ckeditor5_premium_features_realtime_collaboration_remove_channels_entities($entity);
}

/**
 * Implements hook_entity_translation_delete().
 *
 * Remove ckeditor5_channel entities after parent translation entity is deleted.
 */
function ckeditor5_premium_features_realtime_collaboration_entity_translation_delete(EntityInterface $translation): void {
  ckeditor5_premium_features_realtime_collaboration_remove_channels_entities($translation, TRUE);
}

/**
 * Removes all channels entities related to the entity.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   The entity.
 * @param bool $is_translation
 *   Flag for removing translation.
 */
function ckeditor5_premium_features_realtime_collaboration_remove_channels_entities(EntityInterface $entity, bool $is_translation = FALSE): void {
  $uuid = $entity->uuid();

  if (!$uuid) {
    return;
  }

  if ($entity instanceof ChannelInterface) {
    return;
  }

  $storage = Drupal::entityTypeManager()
    ->getStorage(ChannelInterface::ENTITY_TYPE_ID);

  $query = $storage->getQuery()
    ->accessCheck(FALSE)
    ->condition('entity_id', $uuid);

  if ($is_translation) {
    $langcode = $entity->language()->getId();
    $query->condition('langcode', $langcode);
  }

  $ids = $query->execute();

  if (!$ids) {
    return;
  }

  $entities = $storage->loadMultiple($ids);
  $storage->delete($entities);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function ckeditor5_premium_features_realtime_collaboration_editor_update(\Drupal\Core\Entity\EntityInterface $entity) {
  // Send CKEditor 5 bundle to the cloud server after editor is updated.
  // It will be used to export document HTML code in the process of validation
  // when permissions system is used in RTC mode.

  $messenger = Drupal::messenger();
  $format = $entity->id();
  $formatBundle = $format . '_' . time();
  $config = \Drupal::service('config.factory')
    ->getEditable('ckeditor5_premium_features_realtime_collaboration.config');

  $pluginManager = \Drupal::service('plugin.manager.editor');
  $libraryResolver = \Drupal::service('library.dependency_resolver');
  $plugin = $pluginManager->createInstance('ckeditor5');

  $libraries = $plugin->getLibraries($entity);
  $libraries = $libraryResolver->getLibrariesWithDependencies($libraries);
  $libraries = array_filter($libraries);

  $libraryDiscovery = \Drupal::service('library.discovery');
  $files = [];
  foreach ($libraries as $library) {
    $expl = explode('/', $library);
    $info = $libraryDiscovery->getLibraryByName($expl[0], $expl[1]);
    if ($info && $info['js']) {
      foreach ($info['js'] as $item) {
        $files[] = $item['data'];
      }
    }
  }

  $content = [];

  foreach ($files as $file) {
    // Skip jQuery UI files since they cause errors on cloud server.
    if (str_contains($file, 'jquery.ui') || str_contains($file, 'ckeditor5.dialog.fix.js') || str_contains($file, 'jquery-ui')) {
      continue;
    }

    if (str_starts_with($file, 'https://')) {
      $client = \Drupal::httpClient();
      $response = $client->request('GET', $file, []);
      if ($response->getStatusCode() == 200) {
        $fileContent = '/*' . $file . "*/\n" . $response->getBody()
            ->getContents();
        $content[$file] = $fileContent;
      }
      else {
        $messenger->addError("Failed to download external CKEditor 5 library. Editor bundle upload was aborted, please try saving text format again.");
      }
    }
    elseif (file_exists($file)) {
      $fileContent = '/*' . $file . "*/\n" . file_get_contents($file);
      $content[$file] = $fileContent;
    }
  }

  $code = implode("", $content);
  $code .= "window.CKEditorCS=window.CKEditor5.editorClassic.ClassicEditor;";

  $conf = $plugin->getJSSettings($entity);

  // Some plugins cause errors on bundle upload or document export. Those plugins
  // can be excluded here.
  $excludePlugins = [
    'DocumentOutlineAdapter',
    'DocumentOutline',
    'RealtimeAdapter',
    'CommentsAdapter',
    'RemoveIncorrectCollaborationMarkers',
  ];

  $excludeCustomPlugins = \Drupal::moduleHandler()->invokeAll('ckeditor5_premium_features_exclude_bundle_plugins');
  $excludePlugins = array_filter(array_merge($excludePlugins, $excludeCustomPlugins));

  $plugins = array_map(function ($a) {
    return 'CKEditor5.' . $a;
  }, array_filter($conf['plugins']));

  $code .= "\nwindow.CKEditorCS.CKEditorPlugins=[" . implode(',', $plugins) . "]";

  $bundleConfig['cloudServices']['bundleVersion'] = $formatBundle;
  $bundleConfig['removePlugins'] = $excludePlugins;
  $bundleConfig['toolbar'] = $conf["toolbar"];

  $apiAdapter = \Drupal::service('ckeditor5_premium_features.api_adapter');
  $response = $apiAdapter->postEditor($bundleConfig, $code);

  $is409Error = isset($response['code']) && $response['code'] == 409;

  $logger = Drupal::logger('ckeditor5_premium_features_realtime_collaboration');

  if ($is409Error) {
    $messenger->addWarning("CKEditor 5 bundle didn't upload successfully to the cloud. This will cause validation errors on form submit that uses realtime collaboration. Please check recent log messages for details and contact support if you need help solving the issue.");
    $logger->warning('Bundle upload failed. Active plugins: %plugins', ['%plugins' => print_r($plugins, TRUE)]);
    $logger->warning('Bundle upload failed. Server response: %response', ['%response' => $response['message']]);
  }
  elseif ($response) {
    $bundles = $config->get('bundles') ?? [];
    $bundles[$format] = $formatBundle;
    $messenger->addStatus('Uploaded CKEditor5 bundle ' . $formatBundle . ' to the cloud server.');
    $config->set('bundles', $bundles);
    $config->save();
  }
}
