<?php

/**
 * @file
 * Contains CKEditor 5 Premium Features Realtime module install functions.
 */

use Drupal\Core\Url;
use Drupal\ckeditor5_premium_features_realtime_collaboration\Entity\ChannelInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Database\Database;

/**
 * Implements hook_requirements().
 */
function ckeditor5_premium_features_realtime_collaboration_requirements($phase): array {
  $requirements = [];

  if (($phase === 'install')) {
    if (\Drupal::moduleHandler()->moduleExists('ckeditor5_premium_features_collaboration') || defined('COLLABORATION_INSTALLING')) {
      $requirements[] = [
        'description' => t('You cannot install CKEditor 5 Realtime Collaboration and CKEditor 5 Non-realtime Collaboration modules at the same time.'),
        'severity' => REQUIREMENT_ERROR,
      ];
    } else {
      define('COLLABORATION_INSTALLING', TRUE);
    }
  }

  if ($phase == 'runtime') {
    /** @var \Drupal\ckeditor5_premium_features\Config\SettingsConfigHandlerInterface $config_handler */
    $config_handler = \Drupal::service('ckeditor5_premium_features.config_handler.settings');
    if (empty($config_handler->getWebSocketUrl())) {
      $requirements[] = [
        'title' => t('CKEditor Premium'),
        'description' => t('You have to define the Websocket URL in the <a href=":url">CKEditor Premium Settings</a>. Otherwise, the WYSIWYG editor may appear broken.', [
          ':url' => Url::fromRoute('ckeditor5_premium_features.form.settings_general')->setAbsolute()->toString(),
        ]),
        'severity' => REQUIREMENT_ERROR,
      ];
    }

    if (empty($config_handler->getTokenUrl())) {
      $requirements[] = [
        'title' => t('CKEditor Premium'),
        'description' => t('You have to define the Authorization Type in the <a href=":url">CKEditor Premium Settings</a>. Otherwise, the WYSIWYG editor may appear broken.', [
          ':url' => Url::fromRoute('ckeditor5_premium_features.form.settings_general')->setAbsolute()->toString(),
        ]),
        'severity' => REQUIREMENT_ERROR,
      ];
    }
  }

  return $requirements;
}

/**
 * Implements hook_update().
 */
function ckeditor5_premium_features_realtime_collaboration_update_9008() {
  $storageDefinitionKeyId = BaseFieldDefinition::create('string')
    ->setLabel(t('Field Key ID'))
    ->setSetting('not null', TRUE)
    ->setRequired(TRUE);

  $entityDefinition = \Drupal::entityDefinitionUpdateManager();
  $channelKeyColumnReference = $entityDefinition->getFieldStorageDefinition('key_id3', ChannelInterface::ENTITY_TYPE_ID);

  if (!$channelKeyColumnReference) {
    $entityDefinition->installFieldStorageDefinition(
      'key_id',
      ChannelInterface::ENTITY_TYPE_ID,
      ChannelInterface::ENTITY_TYPE_ID,
      $storageDefinitionKeyId
    );

    $schema = Database::getConnection()->schema();

    $channelTable = $entityDefinition->getEntityType(ChannelInterface::ENTITY_TYPE_ID)
      ->getBaseTable();
    $fields = ['entity_id', 'entity_type', 'key_id'];

    $schema->addUniqueKey($channelTable, 'channel_entity', $fields);
  }
}
