<?php

/**
 * @file
 * Contains CKEditor 5 Premium Features Realtime module functions.
 */

declare(strict_types = 1);

use Drupal\ckeditor5_premium_features\Utility\LibraryDefinitionItem;
use Drupal\ckeditor5_premium_features_realtime_collaboration\Element\TextFormat;

/**
 * Implements hook_library_info_build().
 */
function ckeditor5_premium_features_realtime_collaboration_library_info_build(): array {
  /** @var \Drupal\ckeditor5_premium_features\Config\SettingsConfigHandlerInterface $config_handler */
  $config_handler = \Drupal::service('ckeditor5_premium_features.config_handler.settings');

  $libraries = [
    'real-time-collaboration',
    'comments',
    'revision-history',
    'track-changes',
  ];

  $definitions = [];

  foreach ($libraries as $library) {
    $definition = new LibraryDefinitionItem($library, $config_handler->getDllLocation());
    $definition->addRemoteJs($definition->id());

    $definitions[$definition->id()] = $definition->getDefinition();
  }

  return $definitions;
}

/**
 * Implements hook_element_info_alter().
 */
function ckeditor5_premium_features_realtime_collaboration_element_info_alter(array &$info): void {
  if (isset($info['text_format'])) {
    $info['text_format']['#process'][] = [TextFormat::class, 'process'];
  }
}
